In [1]:
from sklearn import datasets

In [36]:
iris = datasets.load_iris()
print(iris.keys())
print(iris['feature_names'])
print(iris['target'])
print(type(iris['target_names']))
print(iris['target_names'])
print(iris['data'])
print(type(iris['data'][0]))
print(len(iris['data']))

dict_keys(['feature_names', 'target', 'target_names', 'DESCR', 'data'])
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
<class 'numpy.ndarray'>
['setosa' 'versicolor' 'virginica']
[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0

In [74]:
import os 
import librosa
import numpy as np
import string as strp

data_dir = '/Users/felipefelix/USP/tcc/dataset/pr_article/S_A_C_Base_Parte-1'

birds = {}
birds['feature_names'] = np.empty(0, dtype = (np.unicode_, 64))
birds['target'] = np.empty(0, dtype = np.int32)
birds['target_names']  = np.empty(0, dtype = (np.unicode_, 64))
#birds['data']  = np.empty(0, dtype = (np.unicode_, 64))
birds['data']  = []


for subdir, dirs, files in os.walk(data_dir):
    for file in files:
        file_split = subdir.split('/')
        if file_split[-1] == 'song':
            file_split[-2] = strp.capwords(file_split[-2])
            if file_split[-2] in birds['target_names'][:]:
                index = np.where(file_split[-2] == birds['target_names'])
                birds['target'] = np.insert(birds['target'], len(birds['target']), index[0][0])
                print("Loading %s" % os.path.join(subdir,file))
                birds['data'].append(librosa.load(os.path.join(subdir, file)))
                #### Cleaning the dataset!
                #if (file.split('.')[-1] != 'mp3'
                #    and file.split('.')[-1] != 'MP3'
                #    and file.split('.')[-1] != 'WAV'
                #    and file.split('.')[-1] != 'flac'
                #    and file.split('.')[-1] != 'wav'):
                #    
                #    print(file.split('.')[-1])
                #    wav = librosa.load(os.path.join(subdir, file))
                
            else:
                birds['target_names'] = np.insert(birds['target_names'], len(birds['target_names']), file_split[-2])
            

Loading /Users/felipefelix/USP/tcc/dataset/pr_article/S_A_C_Base_Parte-1/Aegolius harrisii/song/100010.mp3
Loading /Users/felipefelix/USP/tcc/dataset/pr_article/S_A_C_Base_Parte-1/Aegolius harrisii/song/100011.mp3
Loading /Users/felipefelix/USP/tcc/dataset/pr_article/S_A_C_Base_Parte-1/Aegolius harrisii/song/100012.mp3
Loading /Users/felipefelix/USP/tcc/dataset/pr_article/S_A_C_Base_Parte-1/Aegolius harrisii/song/100013.mp3
Loading /Users/felipefelix/USP/tcc/dataset/pr_article/S_A_C_Base_Parte-1/Aegolius harrisii/song/100014.mp3
Loading /Users/felipefelix/USP/tcc/dataset/pr_article/S_A_C_Base_Parte-1/Aegolius harrisii/song/100016.mp3
Loading /Users/felipefelix/USP/tcc/dataset/pr_article/S_A_C_Base_Parte-1/Aegolius harrisii/song/100017.mp3
Loading /Users/felipefelix/USP/tcc/dataset/pr_article/S_A_C_Base_Parte-1/Aegolius harrisii/song/10002.mp3
Loading /Users/felipefelix/USP/tcc/dataset/pr_article/S_A_C_Base_Parte-1/Aegolius harrisii/song/100022.mp3
Loading /Users/felipefelix/USP/tcc/dat

In [84]:
print(birds['target'][49])
print(birds['target_names'][4])
birds['target_names']

4
Attila Rufus


array(['Aegolius Harrisii', 'Amazilia Versicolor', 'Amazona Pretrei',
       'Anthus Lutescens', 'Attila Rufus', 'Automolus Leucophthalmus',
       'Basileuterus Leucoblepharus', 'Batara Cinerea',
       'Brotogeris Tirica', 'Campephilus Robustus',
       'Camptostoma Obsoletum', 'Campylorhamphus Falcularius',
       'Certhiaxis Cinnamomeus', 'Chiroxiphia Caudata',
       'Chlorophanes Spiza', 'Cichlocolaptes Leucophrus',
       'Clibanornis Dendrocolaptoides', 'Cnemotriccus Fuscatus',
       'Colaptes Campestris'], 
      dtype='<U64')

In [44]:
birds.keys()

dict_keys(['feature_names', 'target', 'target_names', 'data'])

In [49]:
len(birds['target'])

11192