In [1]:
%matplotlib inline

import os 
import librosa
import importlib
import matplotlib
import numpy as np
import string as strp
import pr_util as util
import matplotlib.pyplot as plt
import generate_global_features_2 as ggf

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn import datasets
from sklearn import svm, neighbors
from sklearn.naive_bayes import GaussianNB

importlib.reload(util)
importlib.reload(ggf)

<module 'generate_global_features_2' from '/var/tmp/ff/tcc/code/generate_global_features_2.py'>

In [2]:
num_species      = 20
n_min_per_specie = 20

n_global = 4 # number of global functions
scoring  = 'f1_weighted'
song_or_call = 'song'

data_dirs = util.choose_species(num_species, n_min_per_specie, song_or_call)
print(data_dirs)
print(len(data_dirs))

#data_dirs = ['/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Parte-4/Synallaxis spixi/', 
#             '/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Parte-4/Trogon surrucura/', 
#             '/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Parte-4/Vanellus chilensis/']

#data_dirs = ['/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Parte-1/Basileuterus leucoblepharus/', '/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Parte-4/Theristicus caudatus/', '/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Parte-2/Gnorimopsar chopi/']
#data_dirs_pulse = util.dirs_to_pulse_dirs(data_dirs)


#print(data_dirs_pulse)
#data_dirs_pulse = ['/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Pulsos_Parte-4/Synallaxis spixi/', 
#                 '/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Pulsos_Parte-4/Trogon surrucura/', 
#                 '/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Pulsos_Parte-4/Vanellus chilensis/']



#data_dirs = ['/Users/felipefelix/USP/tcc/dataset/pr_article/syllables/experimentos_100/Synallaxis spixi/', 
#             '/Users/felipefelix/USP/tcc/dataset/pr_article/syllables/experimentos_100/Trogon surrucura/', 
#             '/Users/felipefelix/USP/tcc/dataset/pr_article/syllables/experimentos_100/Vanellus chilensis/']

['/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Parte-3/Pyriglena leucoptera/', '/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Parte-3/Myiodynastes maculatus/', '/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Parte-4/Thraupis palmarum/', '/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Parte-4/Sittasomus griseicapillus/', '/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Parte-3/Poospiza nigrorufa/', '/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Parte-2/Mimus saturninus/', '/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Parte-1/Basileuterus leucoblepharus/', '/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Parte-2/Lathrotriccus euleri/', '/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Parte-4/Trichothraupis melanops/', '/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Parte-3/Polioptila dumicola/', '/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Parte-3/Phleocryptes melanops/', '/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base_Parte-2/Drymophila malura/', '/var/tmp/ff/tcc/dataset/pr_article/S_A_C_Base

In [3]:
print(util.FEATURES)
feat = util.FEATURES[3]

#labels_dict_p, labels_p, data_p = ggf.generate_global_features(n_global, feat, data_dirs_pulse, song_or_call, util.GLOBAL_FUNCTIONS, version = None)

labels_dict_o, labels_o, data_o = ggf.generate_global_features(n_global, feat, data_dirs, song_or_call, util.GLOBAL_FUNCTIONS, version = None)
#labels_dict_f1, labels_f1, data_f1 = ggf.generate_global_features(n_global, feat, data_dirs, song_or_call, util.GLOBAL_FUNCTIONS, version = 'filtered1')
#labels_dict_f2, labels_f2, data_f2 = ggf.generate_global_features(n_global, feat, data_dirs, song_or_call, util.GLOBAL_FUNCTIONS, version = 'filtered2')
#labels_dict_f3, labels_f3, data_f3 = ggf.generate_global_features(n_global, feat, data_dirs, song_or_call, util.GLOBAL_FUNCTIONS, version = 'filtered3')
labels_dict_f4, labels_f4, data_f4 = ggf.generate_global_features(n_global, feat, data_dirs, song_or_call, util.GLOBAL_FUNCTIONS, version = 'filtered4')


# MULTI-FEATURES

#labels_dict_o, labels_o, data_o = ggf.generate_global_multi_features(n_global, ['spec_band', 'spec_cent'], data_dirs, song_or_call, util.GLOBAL_FUNCTIONS, version = None)


['rmse', 'mfcc', 'spec_band', 'spec_cent', 'spec_roll', 'syllable_dur', 'syllable_dur_list', 'zcr']
number of files loaded: 1037
number of files loaded: 1037


In [4]:

print(labels_dict_o)
#print(labels_dict_p)
# print(labels_dict_f1)
# print(labels_dict_f2)
# print(labels_dict_f3)
#print(labels_dict_f4)



print(labels_o)
#print(labels_p)


# print(labels_f1)
# print(labels_f2)
# print(labels_f3)
print(labels_f4)

print(len(labels_o))
#print(len(labels_p))

# print(len(labels_f1))
# print(len(labels_f2))
# print(len(labels_f3))
print(len(labels_f4))

#print(data_o[:10])
#print(data_p[:10])
print(data_f4[:10])

# print(data_f1[:10])
# print(data_f2[:10])
# print(data_f3[:10])

print(len(data_o))
#print(len(data_p))
print(len(data_f4))
# print(len(data_f1))
# print(len(data_f2))
# print(len(data_f3))


{'Phleocryptes Melanops': 10, 'Basileuterus Leucoblepharus': 6, 'Ramphastos Dicolorus': 18, 'Sittasomus Griseicapillus': 3, 'Chiroxiphia Caudata': 14, 'Poospiza Nigrorufa': 4, 'Polioptila Dumicola': 9, 'Tangara Desmaresti': 15, 'Trichothraupis Melanops': 8, 'Xenops Minutus': 12, 'Pyriglena Leucoptera': 0, 'Thraupis Palmarum': 2, 'Aegolius Harrisii': 16, 'Myiodynastes Maculatus': 1, 'Stymphalornis Acutirostris': 19, 'Myiophobus Fasciatus': 13, 'Hypoedaleus Guttatus': 17, 'Lathrotriccus Euleri': 7, 'Mimus Saturninus': 5, 'Drymophila Malura': 11}
[ 0  0  0 ..., 19 19 19]
[ 0  0  0 ..., 19 19 19]
1037
1037
[[ 2332.97555844   114.65944651  2845.92678826  2132.58760267]
 [ 3051.24897615   150.72032409  3509.93077625  2639.27640277]
 [ 2467.68683838   145.37182119  2965.51967485  2202.92774364]
 [ 2774.1307206    284.06922615  5122.30711781   965.24703578]
 [ 2491.42150491   614.0173976   3572.68809871  1486.53219713]
 [ 4849.60265727   793.24894922  6406.47528775  2888.31471357]
 [ 2520.6744

In [ ]:
util.plot_scatter(data_o[:,0], data_o[:,1], labels_o, feat + ' mean', feat + ' std')

In [ ]:
util.plot_scatter(data_f4[:,0], data_f4[:,1], labels_f4, feat + ' mean', feat + ' std')

In [ ]:
util.plot_scatter(data_f1[:,2], data_f1[:,3], labels_f1, feat + ' mean', feat + ' std')

In [ ]:
util.plot_scatter(data_f2[:,2], data_f2[:,3], labels_f2, feat + ' mean', feat + ' std')

In [5]:
def generate_scores(clf, clf_name, data, labels, scoring, cv = 5):
    scores  = cross_val_score(clf, data, labels, n_jobs = -1, cv = cv, scoring = scoring, verbose = 3)
    print(scores)
    print('{0} - {1}: {2:.2f} (+/- {3:.2f})'.format(clf_name, scoring, scores.mean(), scores.std() * 2))


In [ ]:
clf     = neighbors.KNeighborsClassifier(3, weights = 'uniform')

#for scoring in ['f1_weighted', 'f1_micro', 'f1_macro']:
#    print(scoring)
#    generate_scores(clf, 'kNN', data_o, labels_o, scoring)

generate_scores(clf, 'kNN', data_o, labels_o, scoring)

#generate_scores(clf, 'kNN', data_p, labels_p, scoring)

#generate_scores(clf, 'kNN', data_f1, labels_f1, scoring)
#generate_scores(clf, 'kNN', data_f2, labels_f2, scoring)
#generate_scores(clf, 'kNN', data_f3, labels_f3, scoring)
generate_scores(clf, 'kNN', data_f4, labels_f4, scoring)


In [ ]:
clf     = GaussianNB()

generate_scores(clf, 'gNB', data_o, labels_o, scoring)
#generate_scores(clf, 'gNB', data_p, labels_p, scoring)

#generate_scores(clf, 'gNB', data_f1, labels_f1, scoring)
#generate_scores(clf, 'gNB', data_f2, labels_f2, scoring)
#generate_scores(clf, 'gNB', data_f3, labels_f3, scoring)
generate_scores(clf, 'gNB', data_f4, labels_f4, scoring)


In [7]:
clf = svm.SVC(kernel = 'rbf', max_iter=100000000, C = 1, decision_function_shape='ovr')

generate_scores(clf, 'SVM', data_o, labels_o, scoring)
#generate_scores(clf, 'SVM', data_p, labels_p, scoring)

#generate_scores(clf, 'SVM', data_f1, labels_f1, scoring)
#generate_scores(clf, 'SVM', data_f2, labels_f2, scoring)
#generate_scores(clf, 'SVM', data_f3, labels_f3, scoring)
#generate_scores(clf, 'SVM', data_f4, labels_f4, scoring)



[CV]  ................................................................
[CV]  ................................................................
[CV]  ................................................................
[CV]  ................................................................
[CV]  ................................................................


/home/gradmac/fsfelix/.local/lib/python3.5/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[CV] ...................... , score=0.06307012446450531, total=   0.1s


/home/gradmac/fsfelix/.local/lib/python3.5/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/gradmac/fsfelix/.local/lib/python3.5/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/gradmac/fsfelix/.local/lib/python3.5/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[CV] ...................... , score=0.07907156184210963, total=   0.1s
[CV] ..................... , score=0.046738197424892707, total=   0.1s
[CV] ....................... , score=0.0533652361840074, total=   0.1s


/home/gradmac/fsfelix/.local/lib/python3.5/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[CV] ...................... , score=0.06970768368786105, total=   0.2s
[ 0.06307012  0.06970768  0.05336524  0.07907156  0.0467382 ]
SVM - f1_weighted: 0.06 (+/- 0.02)


[Parallel(n_jobs=-1)]: Done   2 out of   5 | elapsed:    0.1s remaining:    0.2s
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    0.2s finished
