In [32]:
import os 
import librosa
import numpy as np
import string as strp

from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm

In [33]:
data_dir = '/Users/felipefelix/USP/tcc/dataset/exp/'

def generate_local_features(file_dir, feat_name, feat_func, y, **kwargs):
    print(kwargs)

    output_file = file_dir + '.' + feat_name + '.txt'

    if not os.path.isfile(output_file):
        print('generating {} for {}...'.format(feat_name, file_dir))
        feature = feat_func(y=y, **kwargs)
        np.savetxt(output_file, feature)
    else:
        print('{} already exists.'.format(output_file))
            
for subdir, dirs, files in os.walk(data_dir):
    for file in files:
        if file[0] != '.' and file.split('.')[-1] == 'mp3':
#            print('{} {} {}'.format(file, dirs, subdir))
            file_dir = subdir + '/' + file
            print('Loading {}...'.format(file_dir))
        
            y, sr = librosa.load(file_dir)
            
            #generate_local_features(file_dir, 'rmse', librosa.feature.rmse, y)
            
            #generate_local_features(file_dir, 'stft', librosa.core.stft, y)
            
            generate_local_features(file_dir, 'mfcc', librosa.feature.mfcc, y)
            
#            feature = librosa.feature.rmse(y = y)
#            np.savetxt(subdir + '/' + file + '.' + 'rmse', feature)
            

Loading /Users/felipefelix/USP/tcc/dataset/exp/Aegolius harrisii/song/10001.mp3...
{}
/Users/felipefelix/USP/tcc/dataset/exp/Aegolius harrisii/song/10001.mp3.rmse.txt already exists.
{}
generating stft for /Users/felipefelix/USP/tcc/dataset/exp/Aegolius harrisii/song/10001.mp3...
{}
/Users/felipefelix/USP/tcc/dataset/exp/Aegolius harrisii/song/10001.mp3.mfcc.txt already exists.
Loading /Users/felipefelix/USP/tcc/dataset/exp/Aegolius harrisii/song/10002.mp3...
{}
/Users/felipefelix/USP/tcc/dataset/exp/Aegolius harrisii/song/10002.mp3.rmse.txt already exists.
{}
generating stft for /Users/felipefelix/USP/tcc/dataset/exp/Aegolius harrisii/song/10002.mp3...
{}
/Users/felipefelix/USP/tcc/dataset/exp/Aegolius harrisii/song/10002.mp3.mfcc.txt already exists.
Loading /Users/felipefelix/USP/tcc/dataset/exp/Brotogeris tirica/song/1000130.mp3...
{}
/Users/felipefelix/USP/tcc/dataset/exp/Brotogeris tirica/song/1000130.mp3.rmse.txt already exists.
{}
generating stft for /Users/felipefelix/USP/tcc/d

KeyboardInterrupt: 

In [64]:
data = np.empty((6, 4))
i = 0
labels = []
for subdir, dirs, files in os.walk(data_dir):
    for file in files:
        #print(file)
        if file.split('.')[-2] == 'mfcc':
            print(subdir.split('/')[-2].title())
            labels.append(subdir.split('/')[-2].title())
            feature = np.loadtxt(subdir + '/' + file)
            data[i][0] = np.mean(feature)
            data[i][1] = np.std(feature)
            data[i][2] = np.max(feature)
            data[i][3] = np.min(feature)
            i += 1

            

Aegolius Harrisii
Aegolius Harrisii
Brotogeris Tirica
Brotogeris Tirica
Campephilus Robustus
Campephilus Robustus


['Aegolius Harrisii',
 'Aegolius Harrisii',
 'Brotogeris Tirica',
 'Brotogeris Tirica',
 'Campephilus Robustus',
 'Campephilus Robustus']

In [65]:
#labels = [0,0,1,1,2,2]
#y = np.array(labels)
y = labels
print(data)
print(y)

[[ -12.31785983  121.9363747   101.24849959 -562.12707307]
 [ -24.76893932  128.23397285   91.46952219 -611.73072135]
 [ -10.60058422   88.61504105  160.13321168 -630.61109061]
 [ -11.51450248   87.21339245  102.67373531 -687.10491681]
 [ -32.19253199   90.29695016   58.58385065 -499.85404376]
 [ -18.21253014   86.12578062  275.4789917  -640.51234996]]
['Aegolius Harrisii', 'Aegolius Harrisii', 'Brotogeris Tirica', 'Brotogeris Tirica', 'Campephilus Robustus', 'Campephilus Robustus']


In [66]:
X_train, X_test, y_train, y_test = train_test_split(data, y, test_size=0.4, random_state=0)


In [67]:
print("Treinamento")
print(X_train)
print(y_train)
print("Teste")
print(X_test)
print(y_test)

Treinamento
[[ -11.51450248   87.21339245  102.67373531 -687.10491681]
 [ -12.31785983  121.9363747   101.24849959 -562.12707307]
 [ -32.19253199   90.29695016   58.58385065 -499.85404376]]
['Brotogeris Tirica', 'Aegolius Harrisii', 'Campephilus Robustus']
Teste
[[ -18.21253014   86.12578062  275.4789917  -640.51234996]
 [ -10.60058422   88.61504105  160.13321168 -630.61109061]
 [ -24.76893932  128.23397285   91.46952219 -611.73072135]]
['Campephilus Robustus', 'Brotogeris Tirica', 'Aegolius Harrisii']


In [68]:
clf = svm.SVC(kernel='rbf', C=1)
clf.fit(X_train, y_train)


SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [69]:
clf.predict(X_test)
clf.score(X_test, y_test) # Retorna f-measure

0.66666666666666663